### ISSUE TITLE
How to deal with text that's initially hidden

### ISSUE THREAD

**Issue by bokand** [WICG/ScrollToTextFragment#17]
To give an example, see any mobile Wikipedia page: e.g. https://en.m.wikipedia.org/wiki/Cat.

Sections after the first one start off in collapsed headings. The text is available in the DOM but isn't displayed to the user unless they expand the relevant section.

These features are author-coded and there's no way in general to detect this case or have the browser automatically expand/display the section. I think there's just 2 options here:

1) Ignore text that's in a `display:none` subtree or hidden obscured/clipped out (this could be done with IntersectionObserver)
2) Allow pages to account for this and automatically expand/display any targeted text. In the example above, Wikipedia automatically expands sections that are linked using an element-id hash: e.g. https://en.m.wikipedia.org/wiki/Cat#Senses.

Option 1 seems unsatisfying so I think we should pursue 2. The most straightforward way would be to apply the CSS `:target` pseudo-class. This ties in with issue #1 which proposes `target-within` since we cannot apply a pseudo-class to text.

**Comment by bryanmcquade** [comment]
Using target or target-within or something similar makes a lot of sense.

I think I'm slightly inclined to use a new pseudoclass here (not reuse target) since existing sites may make use of the existing target pseudoclass in ways that may not make sense for this feature. For example, it used to be the case (doesn't seem so anymore) that stackoverflow would apply a fading highlight to the :target element if you scrolled to a specific answer via the fragment, e.g. https://stackoverflow.com/questions/4652654/how-to-turn-off-word-wrapping-in-html#answer-31272472. I could imagine sites like stackoverflow or others assuming only the items with id's can become target and thus they may apply certain stylings that may not work well for elements we might end up targeting via targetText. So introducing a new pseudoclass seems slightly preferable here, I think.

Another thing to think about is that since we support multiple #targetTexts, we may want to apply our pseudoclass to multiple elements. I don't think that's supported for target pseudo-class and is another case where existing assumptions could break if we re-use the existing class.

**Comment by tigt** [comment]
Chrome has a proposed/partially implemented [Display Lock API](https://github.com/WICG/display-locking/blob/master/README.md) that mentions this exact use-case

**Comment by bokand** [comment]
Yup, content that uses display locking would avoid this issue (a text fragment activation seems similar to find-in-page so that we'd activate an invisible subtree). That said, this allows newly built (assuming the API does eventually ship) content to work well. I think we'd still want an easy path for existing content like Wikipedia expando sections. I think it makes sense to still pursue `:target-within`.

**Comment by domenic** [comment]
Note that the current spec seems to imply `:target` will continue working, as it intends to use "the indicated part of the document", which fuels the `:target` selector.

**Comment by bokand** [comment]
I think all the required tools here are covered by #1 and #2 so I'm going to close in favor of those.
