### ISSUE TITLE
Ideas for better accessibility and privacy

### ISSUE THREAD

**Issue by ghost** [WICG/ScrollToTextFragment#187]
Hi all!

#### 1. Feature-name
Encrypted text with md5.

#### 2. Feature-description
My goal here would be to have an encrypted url in order to hide the part of the information on the network.

#### 2.1 Why?
1. Increase scroll-to-text-fragment privacy, security. 
2. Hashing algorithms can be used to authenticate data. "This allows us to hide what text within the network we are accessing."
3. I chose the md5 algorithm just as a demo, there are alternatives like sha256 etc.

#### 2.2 proof of concept?
![image](https://user-images.githubusercontent.com/95204402/174520590-f4fad16c-99ca-49f1-a52d-2df568e9610b.png)

#### 2.3 Demo?
Input: https://en.wikipedia.org/wiki/History_of_computing#:~:text=The%20first%20recorded,Williams
Output: https://en.wikipedia.org/wiki/History_of_computing#:~:text=5584578475ca03db28e007feedc0bef9 (md5)

#### 3. Notes
I'm not promoting or wanting to promote any product, company, person, technology, service, business. My purpose in referencing the links is for bibliography only.

#### 4. Reference
- http://www.md5.cz/
- https://emn178.github.io/online-tools/md5.html
- https://www.techtarget.com/searchdatamanagement/definition/hashing
- https://www.2brightsparks.com/resources/articles/introduction-to-hashing-and-its-uses.html
- https://www.okta.com/identity-101/hashing-algorithms

**Comment by aphillips** [comment]
I think I understand the proposal, but I'm not sure how it addresses accessibility or privacy concerns. I'll leave that others and comment on the I18N related stuff 😉

The concepts "words" and "lines" are problematic. 

Word-breaking is language dependent. Unicode provides a "convenient default", but this is mainly only good for operations such as cursoring in which the user has low expectations in certain languages. In lengthier texts, the UAX29 word count would be disconnected from reality pretty significantly. It would also vary significantly between browsers and operating systems, making the reference useless. 

Lines depend on wrapping behavior, font size, etc.

**Comment by bokand** [comment]
Hi there!

Perhaps I'm missing something but I'm not sure I understand the motivation. The text directive is part of the URL fragment which is not sent to the network as part of a request and the directive is stripped from the URL before script on the destination page can see it.

Perhaps you could elaborate on the problem you're trying to solve?

**Comment by bokand** [comment]
"Privacy" and "Accessibility" are general aspects of a problem/solution but not actually describing the problem you have.

I don't see above any proposal that relates to accessibility (apologies if I missed it).

In terms of privacy, I see that you want to "hide the part of the information on the network." but in what situations? As I mentioned, when the browser makes a request to a URL containing the text directive, the fragment isn't sent to the server so the text fragment isn't visible on the network so I don't see what problem this would be solving.

Do you have a concrete example of a user flow that this would address? i.e. what steps does the user take? what happens in the system (what network requests/responses are made)? what is the threat/risk that's occurring?

As an example of why it's difficult to evaluate in this general form: the proposal to use a hash instead of the plain text only helps (assuming an attacker can see the fragment) if the page in question requires authentication. If it's a public page, an attacker could capture the hash, load the same URL + hash in their own browser, discover the text.

Additionally, a hash is a one way function. In order for the browser to then determine what text it should highlight it would have to try hashing every n-gram of words on the page which seems impractical.
