### ISSUE TITLE
Unified syntax for URL and selector fragment identifier?

### ISSUE THREAD

**Issue by j9t** [WICG/ScrollToTextFragment#31]
Just a thought quickly typed down—could the idea to also use CSS for fragment identifiers be merged with this draft?

What about, already buying into the name change suggestion in https://github.com/WICG/ScrollToTextFragment/issues/25, providing for both

* ``##target=prefix-,startText,endText,-suffix`` and
* ``##target(selector)``?

This may be reasonably clear and allow for maximum flexibility. A quick thought.

**Comment by bokand** [comment]
Our original idea and proposal was to specify a CSS selector (see the section in the [explainer](https://github.com/WICG/ScrollToTextFragment#css-selector-fragments)) .

This proved to be rather scary from a security point of view since it's possible an attacker might be able to tell whether the target was matched. A CSS selector would allow the attacker to exfiltrate things like csrf tokens which is much more dangerous than plain text.

It's something that we've left the door open to (if someone could find a safe way to expose some CSS selector capabilities, it could be added as a new selector type) but I don't think we want to tie it specifically to this proposal.

**Comment by j9t** [comment]
Got it. Do I understand you right that if the door is open to it, it would still be considered on a higher level? It seems that not much may be needed right now other than a conceptual frame, like a syntax container (as with the parentheses mentioned in the draft).

**Comment by bokand** [comment]
I'm not sure I understand the question. By "leave the door open" I meant that we're trying to design the mechanism such that future work could extend our proposal to allow CSS selectors (e.g. by using a different keyword) but there's lots of work to be done there to ensure it's done in a secure way, specifying the details, gathering consensus among the spec community and browser vendors, etc.
