### ISSUE TITLE
"all of the visible text on the page"

### ISSUE THREAD

**Issue by domenic** [WICG/ScrollToTextFragment#34]
This is not sufficiently well-defined.

Maybe this is intentional, and we mean to use similar user-agent discretion as is done for find-in-page, which has some per-UA heuristics. But I'll provide some advice assuming the desire is complete interoperability.

Here are some potential axes which need to be considered:

- textContent-style vs. innerText-style. textContent is essentially the raw text node content, whereas innerText does a variety of styling-derived transformations, e.g. CSS uppercasing translates to uppercase characters, hiding things with CSS removes them from the text, `<br>`s and other linebreaks become `\n`, and so on.

- Does this search inside shadow trees, or only the light DOM? Probably it should, although this means that existing definitions are not going to be helpful and we'll need to create our own.

- Similarly, do we use DOM order or flat tree order? This is primarily impacted by shadow DOM slotting.

If you have some thoughts on the answers that would be most useful here, I can try to give some guidance on how to precisely define this. Also, if there are other subtleties to consider, that'd be good to know; the above is just off the top of my head.

**Comment by bokand** [comment]
We had a bit of related discussion in https://github.com/WICG/ScrollToTextFragment/pull/29#discussion_r322959047. I think it's important for interop that we specify this with less room for discretion than find-in-page.

> textContent-style vs. innerText-style.

I think we want something more like innerText. We made the search non-case-sensitive because the use case for sensitive was weak and this sidestepped some of these issues. Otherwise, I think the search should occur over something that's more closely related to what the user sees.

> Does this search inside shadow trees / do we use DOM order or flat tree order?

Good point, we didn't consider shadow DOM. I agree it probably should and we should use the flat tree order. Our implementation appears to already do a flat tree traversal so I think it's just a matter of describing our traversal in spec. For the most part, I think it's just a simple traversal that does a text search in text-nodes but I believe there's some "magic" for supporting searching across some nodes (e.g. `this entire <i>line</i> should be matchable`).

@nickburris knows most about this - could you take a crack at this, I think this is the major missing piece from the spec.

By "existing definitions are not going to be helpful", what definitions are you referring to?

**Comment by nickburris** [comment]
Thanks Domenic! I opened PR #37 to start improving the algorithm and would love your thoughts so far.

**Comment by nickburris** [comment]
I think walking the tree and searching each text node's innerText handles things like inline styling (in general, descendant text nodes of text nodes). For example, the `innerText` of `<p>this entire <i>line</i> should be matchable</p>` is "this entire line should be matchable".

@domenic What do you think of this version of the algorithm after #37?

**Comment by bokand** [comment]
Great, I didn't know that! Does this match the Chrome implementation now thought? I remember you mentioned we had some exception to look one child/sibling node away to compensate for text being in different nodes. Was that just the cases like above?

**Comment by nickburris** [comment]
The Chrome implementation doesn't explicitly use innerText, we're using the [find-in-page logic to get text for a given range](https://cs.chromium.org/chromium/src/third_party/blink/renderer/core/editing/finder/find_buffer.cc?l=278&rcl=b81c4ba298ffeb813e9c9ff7ef836f39ed6fb6a3), which does a flat tree traversal and collects text until it hits a block boundary, which I've tried to best replicate using TreeWalker/innerText in the spec.

**Comment by bokand** [comment]
The recent changes made this much more specific. I think we can close this and address any related issues in new issues.

**Comment by bokand** [comment]
Closing as per my last comment, feel free to reopen or file new issues if there's still something left.
